// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbco3zQm_pPf2eV9et2wxl7BVve0ilyWU',
    appId: '1:22775279262:web:86e855161de0c1332a558f',
    messagingSenderId: '22775279262',
    projectId: 'philjobnet-project',
    authDomain: 'philjobnet-project.firebaseapp.com',
    storageBucket: 'philjobnet-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4LK_o81S9oO_fWq6WHHi3HdBZ5V5Ysrg',
    appId: '1:22775279262:android:574758d59062b1062a558f',
    messagingSenderId: '22775279262',
    projectId: 'philjobnet-project',
    storageBucket: 'philjobnet-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxQkAkVMKrDBpJujs_URsKkCsGovJgFlA',
    appId: '1:22775279262:ios:99df2dea3573c8762a558f',
    messagingSenderId: '22775279262',
    projectId: 'philjobnet-project',
    storageBucket: 'philjobnet-project.appspot.com',
    iosBundleId: 'com.example.philjobnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxQkAkVMKrDBpJujs_URsKkCsGovJgFlA',
    appId: '1:22775279262:ios:99df2dea3573c8762a558f',
    messagingSenderId: '22775279262',
    projectId: 'philjobnet-project',
    storageBucket: 'philjobnet-project.appspot.com',
    iosBundleId: 'com.example.philjobnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbco3zQm_pPf2eV9et2wxl7BVve0ilyWU',
    appId: '1:22775279262:web:f23539133cad49d92a558f',
    messagingSenderId: '22775279262',
    projectId: 'philjobnet-project',
    authDomain: 'philjobnet-project.firebaseapp.com',
    storageBucket: 'philjobnet-project.appspot.com',
  );
}
